language: android
jdk: openjdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - android-23
    - android-19
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository

script: ./gradlew connectedAndroidTest